### ISSUE TITLE
[Question]:  GlobalFilter  : after pipeline is no Required in the document description , But it's actually Required,

### ISSUE THREAD

**Issue by wj-stack** [megaease/easegress#820] opened 2022-10-09 01:51 UTC
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

after pipeline is no Required in the document description,

But it's actually Required,

Actually I just need before pipeline

```
wyatt@wyatt-VirtualBox:~/code/api/regs$ echo '
> name: globalFilter-example
> kind: GlobalFilter
> beforePipeline:
>   flow: 
>   - filter: validator
> 
>   filters: 
>   - name: validator
>     kind: Validator 
> ' | egctl object create
Error: 400: {"jsonschemaErrs":["afterPipeline: Must validate one and only one schema (oneOf)","afterPipeline.filters: Invalid type. Expected: array, given: null"]}

```

**Comment by localvar** [comment] 2022-10-10 01:35
hi @wj-stack , I think this issue has already been fixed in #798 and I cannot reproduce it, the fix will be included in the next release. For now, please build from the main branch.

**Closed** 2023-02-04 07:52 UTC
Labels: question
